#' Get a network of features of interest from STRING website
#'
#' \code{plot_features} gets the STRING network or subnetwork of features of interests and save as a SVG file.
#'
#' @param df_mapped A data frame. Mapped data frame generated by \code{STRINGdb}'s method \code{map}.
#' @param colors_vec A named character vector of colors for feature of interest.
#' @param string_db An instantiated STRINGdb reference class. See \code{\link[STRINGdb]{STRINGdb-class}}.
#' @param n_hits Integer. The number of nodes to get from STRING network.
#' @param entire Logical. Return the entire STRING network if \code{TRUE}. Only clusters contain features of interest are returned if \code{FALSE}.
#'
#' @return Return a SVG file of network of features of interest.
#' @import xml2
#' @export
#'
#' @examples
plot_features <- function(df_mapped, colors_vec, string_db, n_hits = 200, entire = FALSE) {
  # extract hits
  hits <- df_mapped$STRING_id[1:n_hits]
  all_clusters <- string_db$get_clusters(hits)
  hits_filt <- df_mapped %>%
    dplyr::filter(gene %in% names(colors_vec)) %>%
    dplyr::filter(!is.na(STRING_id))

  readr::write_excel_csv(hits_filt, "table_features_of_int.csv")

  if (isTRUE(entire)) {
    xml <- get_svg(string_db, hits)
  } else {
    subnetwork_df <- get_cluster_of_int(all_clusters, hits_filt)
    xml <- get_svg(string_db, unlist(all_clusters[subnetwork_df$cluster_index],
                                     recursive = TRUE))
    readr::write_excel_csv(subnetwork_df, "cluster_info_features_of_int.csv")
  }

  # get relevant nodes, then change color and label
  b <- xml_children(xml)[5]
  nodes_set <- xml_children(b)[5:length(xml_children(b))]
  modify_nodes(nodes_set, colors_vec)

  # enlarge font size for labels
  m <- xml_children(z)[1]
  xml_text(m) <- str_replace(xml_text(m), "font-size: 12px;", "font-size: 32px;")

  write_xml(xml, "features_of_int.svg")
}
